INSERT INTO food (name, mood) VALUES ('Pizza', 'lazy');
INSERT INTO food (name, mood) VALUES ('Pasta', 'cheerful');
INSERT INTO food (name, mood) VALUES ('Noodles', 'frantic');
INSERT INTO food (name, mood) VALUES ('Chocolate', 'comfort');
INSERT INTO food (name, mood) VALUES ('Nachos', 'comfort');
INSERT INTO food (name, mood) VALUES ('Garlic Bread', 'comfort');
INSERT INTO food (name, mood) VALUES ('Pizza', 'comfort');
INSERT INTO food (name, mood) VALUES ('Meatballs', 'lazy');
INSERT INTO food (name, mood) VALUES ('Fried Rice', 'lazy');
INSERT INTO food (name, mood) VALUES ('Mac and Cheese', 'comfort');
INSERT INTO food (name, mood) VALUES ('Fried Rice', 'frantic');
INSERT INTO food (name, mood) VALUES ('Pizza', 'cheerful');
INSERT INTO food (name, mood) VALUES ('Sandwich', 'lazy');
INSERT INTO food (name, mood) VALUES ('Grilled Cheese', 'lazy');
INSERT INTO food (name, mood) VALUES ('Ramen', 'comfort');
INSERT INTO food (name, mood) VALUES ('Tomato Soup', 'comfort');
INSERT INTO food (name, mood) VALUES ('Quesadilla', 'lazy');
INSERT INTO food (name, mood) VALUES ('Quesadilla', 'frantic');
INSERT INTO food (name, mood) VALUES ('Enchilada', 'lazy');
INSERT INTO food (name, mood) VALUES ('Pizza', 'lazy');
INSERT INTO food (name, mood) VALUES ('Popcorn', 'frantic');
INSERT INTO food (name, mood) VALUES ('Popcorn', 'cheerful');
INSERT INTO food (name, mood) VALUES ('Soup', 'comfort');
INSERT INTO food (name, mood) VALUES ('Dumplings', 'lazy');
INSERT INTO food (name, mood) VALUES ('Pizza', 'lazy');
INSERT INTO food (name, mood) VALUES ('Ice Cream', 'comfort');
INSERT INTO food (name, mood) VALUES ('Fries', 'frantic');
INSERT INTO food (name, mood) VALUES ('Salad', 'cheerful');
INSERT INTO food (name, mood) VALUES ('Salad', 'frantic');

INSERT INTO users (firstname, lastname, email, admin) VALUES ('Amanda', 'Young', 'amanda.young@example', 'admin')